### PR TITLE
WIP Publish standard using OGC Metanorma template

### PR DESCRIPTION
**Pull request by KoalaGeo**

### CODE REVIEW

**Comment by sgrellet** [comment]
Thanks @KoalaGeo , that's something I'm willing to set up for many of those standards (external & internal).
Did you automatize the EA -> metanorma step in some way ?

**Comment by KoalaGeo** [comment]
@sgrellet that wasn't quite ready yet - hence the Work In Progress WIP. but no worries. I wanted to get the GitHub workflows sorted so it automatically deployed drafts to GitHub Pages.  

What's EA? 

Also, do you know where the source files are for https://docs.ogc.org/is/16-008/16-008.html, they don't appear to be in this repo, maybe https://github.com/CGI-IUGS/geosciml.org/tree/master/doc/geosciml/4.1 ???

**Comment by sgrellet** [comment]
EA for Enterprise Architect. From a standard production point of view, the essence is there; then we can generate a specification document based on EA content and add other content that is specific to a specification doc (ex requirement classes). If non automated, let's say you change a definition in the UML model, you need to propagate the change to the specification document in Metanorma template by hand
As for the source file, @denevers may know more. Eric did you first do a word document that was translated in HTML by OGC staff ?

**Comment by sgrellet** [comment]
I just followed the https://github.com/CGI-IUGS/geosciml.org link. Was not aware of that repo. Is that a 'port' from what we used to have under SVN

**Comment by KoalaGeo** [comment]
http://koalageo.rocks/OGC-GeoSciML/ got automatic metanorma working. 

@ghobona advised to get the word doc from the existing published html doc - there's a link near the top. 

I'll test conversion to adoc from both the docx and the html

**Comment by KoalaGeo** [comment]
> I just followed the https://github.com/CGI-IUGS/geosciml.org link. Was not aware of that repo. Is that a 'port' from what we used to have under SVN

I don't know about SVN, it's before my time! But yes think so - it's from when we migrated to using GitHub pages for hosting CGI, geosciml and erml websites. Also then made the code more democratic - wasn't reliant on BGS or GA to do updates

**Comment by denevers** [comment]
> EA for Enterprise Architect. From a standard production point of view, the essence is there; then we can generate a specification document based on EA content and add other content that is specific to a specification doc (ex requirement classes). If non automated, let's say you change a definition in the UML model, you need to propagate the change to the specification document in Metanorma template by hand As for the source file, @denevers may know more. Eric did you first do a word document that was translated in HTML by OGC staff ?

yes it was done the old way... good old MS Word file

**Pull request merged**
